# Generated by Django 6.0.1 on 2026-01-29 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_job_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='applied_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
