# Generated by Django 6.0.1 on 2026-01-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_jobapplication_applied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='expected_salary',
            field=models.CharField(default='Negotiable', max_length=100),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='full_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='job_type',
            field=models.CharField(default='Remote', max_length=50),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='preferred_location',
            field=models.CharField(default='Worldwide', max_length=150),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
