# Generated by Django 5.2.10 on 2026-01-29 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='job_banners/'),
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Applied', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'jobseeker')},
        ),
    ]
